name: Run Checker

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  run-binary:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3

      - name: Make checker executable
        run: chmod +x ./checker

      - name: Run checker
        run: ./checker flag --file manifesto.txt
