name: Run Checker

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  run-binary:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3

      - name: Make checker executable
        run: chmod +x ./checker

      - name: Run checker and save output
        run: ./checker flag --file manifesto.txt > output.txt

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: checker-output
          path: output.txt
