name: Run Checker

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  run-binary:
    runs-on: macos-latest

    steps:
      # Step 1: checkout the repository
      - uses: actions/checkout@v3

      # Step 2: make checker executable
      - name: Make checker executable
        run: chmod +x ./checker

      # Step 3: run checker and save output
      - name: Run checker
        run: ./checker flag --file manifesto.txt > output.txt

      # Step 4: upload output as artifact
      - uses: actions/upload-artifact@v3
        with:
          name: checker-output
          path: output.txt
